# Generated by Django 2.2.7 on 2019-12-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completiondate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studassignments',
            field=models.FileField(upload_to='students/studassignment/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='assignments',
            field=models.FileField(upload_to='teachers/assignments/'),
        ),
    ]
