# Generated by Django 2.2.7 on 2019-12-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20191216_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='duedate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Competed', 'Completed'), ('Uncompleted', 'Uncompleted')], max_length=100),
        ),
    ]
